services:
  db:
    image: mysql:9
    container_name: entrecol-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=entrecol-db
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: entrecol-phpmyadmin
    ports:
      - 5050:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=123456
    depends_on:
      - db
  backend:
    image: entrecol-backend
    container_name: entrecol-backend
    build:
      context: ./entrecol-backend
      target: development
    volumes:
      - ./entrecol-backend:/usr/src/app
      - ~/.m2:/root/.m2
    ports:
      - 8080:8080
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./entrecol-backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 20s
      timeout: 5s
      retries: 10
      start_period: 60s
  frontend:
    image: entrecol-frontend
    container_name: entrecol-frontend
    build:
      context: ./entrecol-frontend
    volumes:
      - ./entrecol-frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4200:4200
    depends_on:
      backend:
        condition: service_healthy
volumes:
  db-data:
