services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=entrecol-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./entrecol-backend/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./entrecol-backend/src/main/resources/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'root', '-d', 'entrecol-db']
      interval: 10s
      timeout: 5s
      retries: 5
  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=entrecol@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    depends_on:
      - db
  backend:
    image: entrecol-backend
    build:
      context: ./entrecol-backend
    volumes:
      - ./entrecol-backend:/usr/src/app
      - ~/.m2:/root/.m2
    ports:
      - 8080:8080
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/actuator/health']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
  frontend:
    image: entrecol-frontend
    build:
      context: ./entrecol-frontend
    volumes:
      - ./entrecol-frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4200:4200
    depends_on:
      backend:
        condition: service_healthy
volumes:
  db-data:
